### PR TITLE
Bump wrap version to 3.100

### PR DESCRIPTION
**Pull request by nirbheek**
commit ccb7157871196b7e90420cec47d01a0f1cbbb631:

```
Rewrite and update configure checks
* Get rid of unused configure checks
* Get rid of config.h.meson, we can generate it (which is less buggy)
* Add a new option to build the command-line utilities
* Implement symbol visibility and win32 symbol exporting. This
  involved changing lame.h from the original sources, so a copy has
  been included here. This is required for building lame on Windows
  with MSVC.
```

commit 30aab475408151d15bf167fff49310db3b7e603a:

```
Also build the decoder code
```

commit 4fcc73d7488b8fa30c2d8564889f78c6302ee44d:

```
Fix build on Windows, and use lame_dep for tools
This way it's a good test for whether lame_dep works at all.
```

### CODE REVIEW

**Comment by nirbheek** [comment]
Not sure how to make a PR for a new branch, so I made this instead :)

**Comment by legeana** [comment]
> Not sure how to make a PR for a new branch, so I made this instead :)

You can make a PR to master. Repository owners can always change the PR destination after creating the necessary branch.

**Comment by legeana** [comment]
@nirbheek could you please rebase/merge with the current branch to include `LICENSE.build` and updated `readme.txt`?

**Comment by nirbheek** [comment]
Done :)

**Pull request merged**
